### ISSUE TITLE
Upload cookbook 0.1.3 to supermarket

### ISSUE THREAD

**Issue by spuder** [KennaSecurity/chef-slack#10]
The newest cookbook version on the supermarket is 0.1.0. Any plans to upload 0.1.3 to the supermarket?

**Comment by spuder** [comment]
Also, if the cookbook versions were tagged, it would make it easier to point berkshelf to a ref

**Comment by spuder** [comment]
@jro It would be real nice to have the latest version of this great cookbook uploaded to the supermarket. Anything preventing that from happening?

**Comment by spuder** [comment]
Is this project still active?

**Comment by spuder** [comment]
The 🍪  I baked to bribe you are long stale. 
Is slack cookbook an abandoned project? 

@jro @jdoss @wickett @wickett @ebellis @jheuer @kennachicago

**Comment by jdoss** [comment]
No promises but I will see what I can do on my end. :smiley:

**Comment by iennae** [comment]
hey folks, I know this is a pretty old issue at this point, but the chef_slack cookbook might be helpful here. I believe it's a fork or update from this one. If it's not helpful, please let us know in the chef_slack cookbook repo. Thanks!

**Comment by jdoss** [comment]
Sorry for the lack of updates. We did reach out to some people at chef to take this over and https://github.com/chef-cookbooks/chef_slack seems to be an alternative to chef-slack. We are moving away from Chef internally and we haven't had the bandwidth to keep this project up to date.
