### ISSUE TITLE
Is this cookbook dead?

### ISSUE THREAD

**Issue by spuder** [KennaSecurity/chef-slack#11]
The owner appears to have recently changed from risk-io/chef-slack to KennaSecurity/chef-slack. 

There are issues that aren't getting any responses. Is this cookbook dead?

**Comment by zeroedin** [comment]
Would like to know as well, is this worth integrating?

**Comment by jdoss** [comment]
It's not dead yet. (https://youtu.be/dGFXGwHsD_A?t=58) We are working on getting PRs merged and a new version pushed out.

**Comment by zeroedin** [comment]
👍
